name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ------------ 步骤 1: 初始化环境 ------------
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # ------------ 步骤 2: 安装混淆工具 ------------
      - name: Setup Obfuscator
        run: npm install -g javascript-obfuscator@4.0.0  # 固定版本避免兼容性问题‌:ml-citation{ref="4" data="citationList"}

      # ------------ 步骤 3: 获取原始代码 ------------
      - name: Fetch source code
        run: |
          wget -O origin.js \
          https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js

      # ------------ 步骤 4: 优化混淆配置 ------------
      - name: Generate config file
        run: |
          cat > obfs-config.json <<EOF
          {
            "compact": true,
            "identifierNamesGenerator": "hexadecimal",
            "renameGlobals": true,
            "stringArray": true,
            "stringArrayEncoding": "base64",  # 改用 base64 替代 rc4‌:ml-citation{ref="6" data="citationList"}
            "stringArrayThreshold": 0.5,      # 降低字符串处理频率‌:ml-citation{ref="2" data="citationList"}
            "selfDefending": false,           # 禁用自保护机制减少开销‌:ml-citation{ref="3" data="citationList"}
            "simplify": true                  # 启用代码简化优化‌:ml-citation{ref="3" data="citationList"}
          }
          EOF

      # ------------ 步骤 5: 执行混淆操作 ------------
      - name: Obfuscate code
        run: |
          javascript-obfuscator origin.js \
            --config obfs-config.json \
            --output _worker.js

      # ------------ 步骤 6: 提交生成文件 ------------
      - name: Commit artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ":arrow_up: update optimized worker"
          file_pattern: |
            _worker.js
            obfs-config.json
