# 文件路径: .github/workflows/Obfuscate.yml
name: BPB Panel Obfuscation

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 1 * * *"  # 每天 UTC 时间 01:00 执行

permissions:
  contents: write  # 允许提交代码

jobs:
  obfuscate-worker:
    runs-on: ubuntu-latest

    steps:
      # ------------ 初始化步骤 ------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      # ------------ 环境准备 ------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Obfuscator
        run: npm install -g javascript-obfuscator@4.0.0 --silent

      # ------------ 获取原始代码 ------------
      - name: Download source
        run: |
          wget --retry-connrefused --tries=3 \
            -O "${{ github.workspace }}/origin.js" \
            https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js

      # ------------ 生成配置文件 (修复路径关键) ------------
      - name: Create config file
        run: |
          CONFIG_PATH="${{ github.workspace }}/obfs-config.json"
          
          # 生成配置文件
          cat > $CONFIG_PATH <<EOF
          {
            "compact": true,
            "controlFlowFlattening": false,  # 禁用高开销选项
            "deadCodeInjection": false,
            "identifierNamesGenerator": "hexadecimal",
            "renameGlobals": true,
            "stringArray": true,
            "stringArrayEncoding": "base64",
            "stringArrayThreshold": 0.5,
            "selfDefending": false,
            "simplify": true
          }
          EOF

          # 验证配置文件
          echo "配置文件路径: $(realpath $CONFIG_PATH)"
          ls -l "$CONFIG_PATH"

      # ------------ 混淆执行 ------------
      - name: Obfuscate code
        run: |
          cd "${{ github.workspace }}"  # 强制切换工作目录
          
          echo "当前目录文件列表:"
          ls -l
          
          # 执行混淆（使用绝对路径）
          javascript-obfuscator ./origin.js \
            --config "${{ github.workspace }}/obfs-config.json" \
            --output ./_worker.js

          # 验证输出文件
          [ -s "./_worker.js" ] || (echo "输出文件生成失败"; exit 1)

      # ------------ 提交结果 ------------
      - name: Commit obfuscated file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ":lock: 自动更新混淆代码"
          file_pattern: |
            _worker.js
            obfs-config.json
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
