# 文件路径: .github/workflows/Obfuscate.yml
name: BPB Panel Obfuscation (Optimized)

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 1 * * *"  # 每天 UTC 时间 01:00 执行

permissions:
  contents: write

jobs:
  obfuscate-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # 限制最大执行时间

    steps:
      # ------------ 初始化步骤 ------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ------------ 环境优化 ------------
      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"  # 指定精确版本确保稳定性
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Generate package.json
        run: |
          if [ ! -f package.json ]; then
            echo '{"name": "github-actions-obfuscator"}' > package.json
          fi

      - name: Install Dependencies (Cached)
        run: npm install --package-lock javascript-obfuscator@4.0.0

      # ------------ 获取源码 ------------
      - name: Download Source Code
        run: |
          wget --retry-connrefused --tries=3 --timeout=30 \
            -O "${{ github.workspace }}/origin.js" \
            https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js

      # ------------ 性能优化混淆配置 ------------
      - name: Create Optimized Config
        run: |
          cat > obfs-config.json <<EOF
          {
            "compact": true,
            "controlFlowFlattening": false,      # 禁用高消耗选项
            "deadCodeInjection": false,          # 禁用死代码注入
            "identifierNamesGenerator": "hexadecimal",
            "renameGlobals": true,
            "stringArray": true,
            "stringArrayEncoding": "base64",     # 比 rc4 性能更好
            "stringArrayThreshold": 0.75,        # 降低处理频率
            "simplify": true,
            "transformObjectKeys": false,        # 禁用对象键转换
            "unicodeEscapeSequence": false        # 禁用 Unicode 转义
          }
          EOF

      # ------------ 执行混淆 ------------
      - name: Run Obfuscation
        run: |
          echo "当前工作目录: $(pwd)"
          ls -l
          
          # 增加内存分配
          export NODE_OPTIONS="--max-old-space-size=4096"
          
          npx javascript-obfuscator \
            --config obfs-config.json \
            --output ${{ github.workspace }}/_worker.js \
            ${{ github.workspace }}/origin.js

          # 验证输出文件
          if [ ! -s "${{ github.workspace }}/_worker.js" ]; then
            echo "::error::混淆文件生成失败"
            exit 1
          fi

      # ------------ 提交结果 ------------
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ":lock: [Optimized] 自动更新混淆代码"
          file_pattern: |
            _worker.js
            obfs-config.json
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
